# Generated by Django 4.1 on 2022-08-19 19:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.IntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MountainPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=254)),
                ('other_titles', models.CharField(max_length=254, null=True)),
                ('connect', models.CharField(max_length=64, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('n', 'new'), ('p', 'pending'), ('a', 'accepted'), ('r', 'rejected')], default='new', max_length=1)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain_pass.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='MountainPassImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=128, null=True)),
                ('mountainpass', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mountain_pass.mountainpass')),
            ],
        ),
        migrations.AddField(
            model_name='mountainpass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain_pass.tourist'),
        ),
    ]
