# Generated by Django 4.1 on 2022-08-29 11:37

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MountainPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(default='title', max_length=254)),
                ('other_titles', models.CharField(blank=True, max_length=254, null=True)),
                ('connect', models.CharField(blank=True, max_length=64, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='new', max_length=8)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('height', models.IntegerField()),
                ('level_winter', models.CharField(blank=True, default='', max_length=3)),
                ('level_spring', models.CharField(blank=True, default='', max_length=3)),
                ('level_summer', models.CharField(blank=True, default='', max_length=3)),
                ('level_autumn', models.CharField(blank=True, default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='MountainPassImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('binary_image', models.BinaryField(blank=True, editable=True, null=True)),
                ('title', models.CharField(max_length=128, null=True)),
                ('mountainpass', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mountain_pass.mountainpass')),
            ],
        ),
        migrations.AddField(
            model_name='mountainpass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mountain_pass', to='mountain_pass.tourist'),
        ),
    ]
