# Generated by Django 4.1 on 2022-08-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0002_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountainpass',
            name='level',
        ),
        migrations.AddField(
            model_name='mountainpass',
            name='autumn',
            field=models.CharField(choices=[('1', '1А'), ('2', '1Б'), ('3', '1Б*'), ('4', '2А'), ('5', '2Б*'), ('6', '2Б'), ('7', '3А'), ('8', '3Б'), ('9', '3Б*')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='mountainpass',
            name='spring',
            field=models.CharField(choices=[('1', '1А'), ('2', '1Б'), ('3', '1Б*'), ('4', '2А'), ('5', '2Б*'), ('6', '2Б'), ('7', '3А'), ('8', '3Б'), ('9', '3Б*')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='mountainpass',
            name='summer',
            field=models.CharField(choices=[('1', '1А'), ('2', '1Б'), ('3', '1Б*'), ('4', '2А'), ('5', '2Б*'), ('6', '2Б'), ('7', '3А'), ('8', '3Б'), ('9', '3Б*')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='mountainpass',
            name='winter',
            field=models.CharField(choices=[('1', '1А'), ('2', '1Б'), ('3', '1Б*'), ('4', '2А'), ('5', '2Б*'), ('6', '2Б'), ('7', '3А'), ('8', '3Б'), ('9', '3Б*')], default='', max_length=1),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
