# Generated by Django 4.1 on 2022-08-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0005_rename_autumn_mountainpass_lvl_autumn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mountainpass',
            old_name='coords',
            new_name='coordinates',
        ),
    ]
